allowBuilds:
  '@coinbase/x402': set this to true or false
  '@opensea/seaport-js': set this to true or false
  bigint-buffer: set this to true or false
  bufferutil: set this to true or false
  esbuild: set this to true or false
  keccak: set this to true or false
  opensea-js: set this to true or false
  secp256k1: set this to true or false
  utf-8-validate: set this to true or false
